// src/components/authorization/Authorization.tsx
import { observer } from 'mobx-react';
import { Link } from "react-router-dom";
import User from './User';
import store from '../../store/Store';

const Authorization = observer(() => {
  let users = store.user.userList;

  return (
    <div className="authorization">
      <div>Choose user</div>
      <div className="user-list">
        <Link to="/home">
          {users.map((user) => {
            return <User key={user.id} {...user} />
          })}
        </Link>
      </div>
    </div>
  )
});

export default Authorization;

// src/components/authorization/Authorization.vue
<template>
<div class="authorization">
  <div>Choose user</div>
  <div class="user-list">
    <Link to="/home">
      <User 
        v-for="user in userList"
        :key="user.id"
        :userName="user.userName"
        :userSrc="user.userSrc"
        :id="user.id"
      />
    </Link>
  </div>
</div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import User from './User.vue'
import Link from '../pages/Link.vue'
import { useStore } from '../../store/store'

export default defineComponent({
  components: {
    User,
    Link
  },
  setup() {
    let store = useStore();
    let userList = computed(() => store.state.userList)

    return {
      userList,
    }
  },
})
</script>
