// src/components/authorization/User.tsx
import { observer } from 'mobx-react';
import { userData } from '../../store/helpers/interfaceList';
import store from '../../store/Store';

const User = observer((props: userData) => {
  let { userName, userSrc, id } = props;
  let setUserData = () => store.user.setUserData(id);

  return (
    <div className="user-link" onClick={setUserData}>
      <div className="icon-wrapper">
        <div 
            className="icon"
            style={{ background: `url(${userSrc}) 50% 30% / cover` }}>
          </div>
        </div>
        <div className="action__userName">{ userName }</div>
    </div>
  )
});

export default User;

// src/components/authorization/User.vue
<template>
  <div class="user-link" @click="setUserData(id)">
    <div class="icon-wrapper">
        <div 
          class="icon"
          :style="{ background: `url(${userSrc}) 50% 30% / cover` }">
        </div>
      </div>
      <div class="action__userName">{{ userName }}</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { mapMutations } from 'vuex'

export default defineComponent({
  props: {
    userSrc: String,
    userName: String,
    id: String,
  },
  methods: {
    ...mapMutations(['setUserData'])
  }
})
</script>
