// src/components/main/EditTodo.vue
<template>
  <div class="modal-wrapper">
    <div class="modal">
      <div>New Task</div>
      <form class="modal__form" @submit.prevent="saveTodo">
        <div class="modal__content">
          <div class="label-list">
            <label 
              v-for="inputData in INPUT_LIST_DATA"
              :key="inputData"
              :for="inputData"
              :class="inputData">
              {{ inputData }}:
            </label>
          </div>
          <div class="input-list">
            <div>{{ author }}</div>
            <textarea
              class="modal__textarea" 
              type="text" 
              :id="INPUT_LIST_DATA[1]" 
              :value="newTodo[0]" 
              @input="(event) => updateNewTodo(event, 0)"
              required
            />
            <TodoItem 
              v-for="(item, index) in newTodo.slice(0,3)"
              :key="[`${item}-id`]"
              :index="index"
              :change="(event) => updateNewTodo(event, index+1)"
            />
          </div>
        </div>
        <input type="submit" class="modal__btn_add" value="Save" />
        <input 
          type="reset" 
          class="modal__btn" 
          value="Cancel" 
          @click="closeEditTodo" 
        />
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import { mapActions } from 'vuex'
import { useStore } from '../../store/store'
import TodoItem from './TodoItem.vue'

export default defineComponent({
  setup() {
    let store = useStore();
    let INPUT_LIST_DATA = computed(() => store.state.INPUT_LIST_DATA);
    let author = computed(() => store.state.userData.userName);
    let newTodo = computed(() => store.state.newTodo);
    let updateNewTodo = (event: Event, index: number) => store.commit('updateNewTodo', ({ event, index }));

    return {
      INPUT_LIST_DATA,
      author,
      updateNewTodo,
      newTodo,
    }
  },
  methods: {
    ...mapActions(['saveTodo', 'closeEditTodo'])
  },
  components: {
    TodoItem
  }
})
</script>

// src/components/main/EditTodo.tsx
import { observer } from 'mobx-react-lite';
import { INPUT_LIST_DATA } from '../../store/helpers/constants';
import store from '../../store/Store';
import EditItem from './EditItem';

const EditTodo = observer(() => {
  let author = store.user.userData.userName;
  let { newTodo, updateNewTodo, closeEditTodo, saveTodo } = store.todo;
  
  return (
    <div className="modal-wrapper">
    <div className="modal">
      <div>New Task</div>
      <form className="modal__form" onSubmit={saveTodo}>
        <div className="modal__content">
          <div className="label-list">
            {INPUT_LIST_DATA.map((data) => {
              return <label key={data} className={data} htmlFor={data}>{data}</label>
            })}
          </div>
          <div className="input-list">
            <div>{ author }</div>
            <textarea
              className="modal__textarea" 
              id="text" 
              value={newTodo.text} 
              onInput={(event: React.ChangeEvent<HTMLTextAreaElement>) => updateNewTodo(event, 'text')}
              required
            />
            {INPUT_LIST_DATA.slice(2).map((data, index) => {
              return <EditItem data={data} index={index} key={data}/>
            })}
          </div>
        </div>
        <input type="submit" className="modal__btn_add" value="Save" />
        <button 
          type="reset" 
          className="modal__btn"
          onClick={closeEditTodo}>
            Cancel
        </button>
      </form>
    </div>
  </div>
  )
});

export default EditTodo;
