// src/components/main/Main.tsx
import { observer } from 'mobx-react';
import store from '../../store/Store';
import CommentList from './CommentList';
import EditTodo from './EditTodo';
import TodoList from './TodoList';

const Main = observer(() => {
  let isShowEdit = store.todo.isShowEdit;
  let isShowComments = store.comment.isShowComments;
  let changeShowEdit = store.todo.changeShowEdit;

  return (
    <main className="main">
    <div className="main__header">
      <div className="main__title">
        You’ve got 
        <span className="todo-number"> 7 task </span> 
        today
      </div>
      <button className="main__btn_add" onClick={changeShowEdit}>Add New</button>
    </div>
    <div className="all-todos">
      <TodoList isActive={true}/>
      <TodoList isActive={false} />
    </div>
    { isShowEdit && <EditTodo /> }
    { isShowComments && <CommentList /> }
  </main>
  )
})

export default Main;

// src/components/main/Main.vue
<template>
  <main class="main">
    <div class="main__header">
      <div class="main__title">
        You’ve got 
        <span class="todo-number"> 7 task </span> 
        today
      </div>
      <button class="main__btn_add" @click="changeVisibilityEditTodo">Add New</button>
    </div>
    <div class="all-todos">
      <TodoList :isActive="true">On Hold</TodoList>
      <TodoList :isActive="false">Completed</TodoList>
    </div>
    <EditTodo v-if="isShowEditTodo" />
    <Comments v-else-if="isShowComments"/>
  </main>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue'
import { mapMutations } from 'vuex'
import TodoList from './TodoList.vue'
import { useStore } from '../../store/store'
import EditTodo from './EditTodo.vue'
import Comments from './Comments.vue'

export default defineComponent({
  setup () {
     const store = useStore();
    
    return {
      isShowEditTodo: computed(() => store.state.isShowEditTodo),
      isShowComments: computed(() => store.state.isShowComments),
    }
  },
  methods: {
    ...mapMutations(['changeVisibilityEditTodo'])
  },
  components: {
    TodoList,
    EditTodo,
    Comments
  },
})
</script>
