// src/components/main/TodoList.tsx
import classNames from 'classnames';
import { observer } from 'mobx-react';
import React from 'react'
import store from '../../store/Store';
import Todo from './Todo'

interface Props {
  isActive: boolean
}

const TodoList = observer((props: Props) => {
  let { isActive } = props;
  let data = store.todoList.getTodoList(isActive);
  let className = classNames({
    'main-item': true,
    'main-item_inactive': !isActive
  });

  return (
    <section className={className}>
      <div className="main-item__title">
        { isActive ? 'On Hold' : 'Completed' }
        <span className="inactive">inactive</span>
      </div>
      <ul className="todo__list">
        { data.map((todo) => {
            return <Todo key={todo.id} {...todo} />
        })}
      </ul>
    </section>
  )
})

export default TodoList;

// src/components/main/TodoList.vue
<template>
  <section class="main-item" :class="{ 'main-item_inactive': !isActive }">
    <div class="main-item__title">
      <slot></slot>
      <span v-show="!isActive" class="inactive">inactive</span>
    </div>
    <ul class="todo__list">
      <Todo 
        v-for="todo in todoList" 
        :key="todo.id"
        :text="todo.text"
        :status="todo.status"
        :progress="todo.progress"
      />
    </ul>
  </section>
</template>

<script lang="ts">
import { defineComponent, computed } from 'vue'
import Todo from './Todo.vue'
import { useStore } from '../../store/store'

export default defineComponent({
  props: {
    isActive: {type: Boolean, default: false }
  },
  setup(props) {
    let store = useStore();
    let todoList = computed(() => store.getters.todoList(props.isActive));
    
    return {
      todoList
    }
  },
  components: {
    Todo
  },
})
</script>
