// src/components/pages/Home.vue
<template>
  <Loading v-if="isLoading"/>
  <div class="app-wrapper">
    <div class="app" v-show="!isLoading">
      <Header />
      <div class="main-wrapper">
        <Main />
        <ActionList />
      </div>
    </div>
  </div>
</template>


<script lang="ts">
import { computed, defineComponent } from 'vue'
import Header from '../header/Header.vue';
import Main from '../main/Main.vue'
import ActionList from '../actions/ActionList.vue';
import Loading from '../pages/Loading.vue';
import { useStore } from '../../store/store';

export default defineComponent({
  setup() {
    const store = useStore();

    return {
      isLoading: computed(() => store.state.isLoading)
    }
  },
  components: {
    Header, 
    Main,
    ActionList,
    Loading
  }
})
</script>

// src/components/home/Home.tsx
import Header from '../header/Header'
import Main from '../main/Main'
import { observer } from "mobx-react";
import store from "../../store/Store";
import ActionList from "../action/ActionList";

const Home = observer(() => {
  let isLoading = store.isLoading;

  return (
    <>
      { !isLoading ? (
          <div className="app-wrapper">
            <div className="app">
              <Header />
              <div className="main-wrapper">
                <Main />
                <ActionList />
              </div>
            </div>
          </div>
        ) : (
          <div className="spin-wrapper">
            <div className="spinner">
            </div>
            <div className="spinner__text">Loading...</div>
          </div>
        )
      }
    </>
  )
});

export default Home;
