// src/components/Modal.tsx
import React from 'react';
import { observer } from 'mobx-react';

import store from 'src/store/Store';

const Modal = observer(() => {
    let className = store.getClassNameModal();
    let setShowModal = () => store.setShowModal(false);

    return (
        <div className={className}>
            <div className="modal">
                <div>Вы проиграли</div>
                <button className="btn btn-modal" onClick={setShowModal}>ОК</button>
            </div>
        </div>
    );
})

export default Modal;

// src/components/Modal.vue
<template>
  <div class='modal-wrapper' v-if="isShowModal">
    <div class="modal">
      <div>Вы проиграли</div>
      <button class="btn btn-modal" @click="closeModal">ОК</button>
    </div>
  </div>
</template>


<script lang="ts">
import { defineComponent, computed } from 'vue'
import { useStore } from '../store/store'
import { mapMutations } from 'vuex'

export default defineComponent({
  setup () {
    const store = useStore()
    
    return {
      isShowModal: computed(() => store.state.isShowModal)
    }
  },
  methods: {
    ...mapMutations(['closeModal'])
  }
})
</script>
