// src/components/action/ActionList.tsx
import { observer } from "mobx-react";
import store from "../../store/Store";
import ActionItem from "./ActionItem";

const ActionList = observer(() => {
  let actionList = store.action.actionList
  return (
    <div className="action-list">
      { actionList.map((action) => {
        return <ActionItem key={action.id} {...action} />
      })}
  </div>
  )
});

export default ActionList;

// src/components/actions/ActionList.vue
<template>
  <div class="action-list">
      <ActionItem 
        v-for="action in actionList"
        :key="action.id"
        :userName="action.userName"
        :text="action.text"
        :time="action.time"
        :userSrc="action.userSrc"
        :subtext="action.subtext"
      />
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from 'vue'
import ActionItem from './Action.vue'
import { useStore } from '../../store/store'

export default defineComponent({
  setup() {
    let store = useStore();

    return {
      actionList: computed(() => store.state.actionList)
    }
  },
  components: {
    ActionItem
  }
})
</script>
